######################################################################
# General configurations
######################################################################
title: Simple Events
description: Passing data between entities - No strings attached !!
logo: SiteLogo.png

######################################################################
# Site URL change it to your real URL when committing
######################################################################
url: http://jsinh.in/simpleevents

######################################################################
# Owner / Site information
######################################################################
owner:
  name: Jsinh
  email: jachauhan@gmail.com
  twitter: _jsinh
  stackexchange: jsinh
  github: jsinh/simpleevents
  google_plus: jachauhan

######################################################################
# Menu link configurations
######################################################################
links:
  - title: Roadmap
    url: /roadmap
    external: false
  - title: License
    url: /license
    external: false
  - title: About
    url: /about
    external: false

######################################################################
# External support integration
######################################################################
disqus_shortname: simpleevents
google_analytics: UA-47710194-1

######################################################################
# Jekyll stuffs
######################################################################
markdown: redcarpet
highlighter: pygments

######################################################################
# Site configuration
######################################################################
permalink: /:title
relative_permalinks: true